package br.com.expenseController.persistence;


/**
* br/com/expenseController/persistence/PeriodPersistenceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from expenseController.idl
* Quarta-feira, 23 de Outubro de 2019 14h06min58s BRST
*/

public interface PeriodPersistenceOperations 
{
  boolean insert (br.com.expenseController.Period period);
  boolean update (br.com.expenseController.Period period);
  boolean remove (br.com.expenseController.Period period);
  br.com.expenseController.Period load (int code);
  br.com.expenseController.Period[] loadAll ();
} // interface PeriodPersistenceOperations
