package br.com.expenseController.persistence;


/**
* br/com/expenseController/persistence/TagPersistence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from expenseController.idl
* Quarta-feira, 23 de Outubro de 2019 14h06min58s BRST
*/

public interface TagPersistence extends TagPersistenceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TagPersistence
