package br.com.expenseController.persistence;


/**
* br/com/expenseController/persistence/TagPersistenceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from expenseController.idl
* Quarta-feira, 23 de Outubro de 2019 14h06min58s BRST
*/

public interface TagPersistenceOperations 
{
  boolean insert (br.com.expenseController.Tag tag);
  boolean update (br.com.expenseController.Tag tag);
  boolean remove (br.com.expenseController.Tag tag);
  br.com.expenseController.Tag load (int code);
  br.com.expenseController.Tag[] loadAll ();
} // interface TagPersistenceOperations
