package br.com.expenseController.persistence;


/**
* br/com/expenseController/persistence/TransactionPersistenceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from expenseController.idl
* Quarta-feira, 23 de Outubro de 2019 14h06min58s BRST
*/

public interface TransactionPersistenceOperations 
{
  boolean insert (br.com.expenseController.Transaction transaction);
  boolean update (br.com.expenseController.Transaction transaction);
  boolean remove (br.com.expenseController.Transaction transaction);
  br.com.expenseController.Transaction load (int code);
  br.com.expenseController.Transaction[] loadAll ();
  br.com.expenseController.Transaction[] loadPeriod (br.com.expenseController.Period Period);
} // interface TransactionPersistenceOperations
